{% set name = "torchsurv" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchsurv-{{ version }}.tar.gz
  sha256: da67f1e229e63b9c94b48a886c6a79d1bed687da0e59c770f1030f9d837911bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42.0
    - wheel
    - pip
  run:
    - python >=3.8
    - pytorch
    - scipy
    - numpy
    - torchmetrics

test:
  imports:
    - torchsurv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://opensource.nibr.com/torchsurv
  summary: Deep survival analysis made easy with pytorch
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pkrusche
    - kruscpe1
    - tcoroller
